// This file contains the query keys used in the app by @tanstack/react-query
export enum QueryKey {
  ADDRESSES = 'addresses',
  AVERAGE_DELIVERY_TIME = 'averageDeliveryTime',
  TRENDING = 'trending',
  CATEGORY = 'category',
  CATEGORIES = 'categories',
  CATEGORY_BREAKDOWN = 'categoryBreakdown',
  CHEAP_PRODUCTS = 'cheapProducts',
  DEALS = 'deals',
  EVENT = 'event',
  EVENTS = 'events',
  FAVORITES = 'favorites',
  NEW_PRODUCTS = 'newProducts',
  ORDERS = 'orders',
  ORDER_AGAIN = 'orderAgain',
  ORDER_DETAILS = 'orderDetails',
  POPPAY_DISCOUNT = 'poppayDiscount',
  PRICES = 'prices',
  PRODUCT = 'product',
  RECOMMENDATIONS = 'recommendations',
  UNIVERSITIES = 'universities',
  UNIVERSITY = 'university',
  USERDATA = 'userData',
  VERSION = 'version',
}
